In [37]:
import pandas as pd

In [42]:
cd I:\NorMITs Land Use\2023\import\ONS-validation\soc_status_active_age

I:\NorMITs Land Use\2023\import\ONS-validation\soc_status_active_age

In [43]:
soc = pd.read_csv(r"soc_lsoa_16-74.csv")

In [44]:
soc

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Age (D) (5 categories) Code,Age (D) (5 categories),Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
0,E01000001,City of London 001A,1,Aged 15 years and under,-8,Does not apply,125
1,E01000001,City of London 001A,1,Aged 15 years and under,1,"1. Managers, directors and senior officials",0
2,E01000001,City of London 001A,1,Aged 15 years and under,2,2. Professional occupations,0
3,E01000001,City of London 001A,1,Aged 15 years and under,3,3. Associate professional and technical occupa...,0
4,E01000001,City of London 001A,1,Aged 15 years and under,4,4. Administrative and secretarial occupations,0
...,...,...,...,...,...,...,...
1783595,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,5,5. Skilled trades occupations,0
1783596,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,6,"6. Caring, leisure and other service occupations",0
1783597,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,7,7. Sales and customer service occupations,0
1783598,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,8,"8. Process, plant and machine operatives",0
1783599,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,9,9. Elementary occupations,0

In [71]:
soc.Observation.sum()

59597725

In [73]:
# Check children do not have SOC
soc_children = soc[(soc['Age (D) (5 categories) Code']==1)&(soc['Occupation (current) (10 categories) Code']>0)].Observation.sum()
print(soc_children)

0

In [76]:
soc_74 = soc[soc['Age (D) (5 categories) Code']<5]

In [77]:
soc_74.Observation.sum()

54457368

In [78]:
soc_75 = soc[(soc['Age (D) (5 categories) Code']==5)]

In [79]:
soc_75.Observation.sum()

5140357

In [80]:
soc_74.Observation.sum()+soc_75.Observation.sum()

59597725

In [ ]:
# Remove age bands

In [81]:
soc_74_no_age = soc_74.drop(soc_74.columns[[2, 3]], axis=1)

In [82]:
soc_75_no_age = soc_75.drop(soc_75.columns[[2, 3]], axis=1)

In [84]:
soc_74_no_age.Observation.sum()+soc_75_no_age.Observation.sum()

59597725

In [58]:
# Aggregate children and active population at zone and soc category with no age

In [85]:
soc_active_group = soc_74_no_age.groupby(['Lower layer Super Output Areas Code',
                       'Lower layer Super Output Areas',
                       'Occupation (current) (10 categories) Code',
                       'Occupation (current) (10 categories)']).sum().reset_index()

In [87]:
soc_active_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
0,E01000001,City of London 001A,-8,Does not apply,481
1,E01000001,City of London 001A,1,"1. Managers, directors and senior officials",191
2,E01000001,City of London 001A,2,2. Professional occupations,396
3,E01000001,City of London 001A,3,3. Associate professional and technical occupa...,178
4,E01000001,City of London 001A,4,4. Administrative and secretarial occupations,38
...,...,...,...,...,...
356715,W01002040,Vale of Glamorgan 015F,5,5. Skilled trades occupations,82
356716,W01002040,Vale of Glamorgan 015F,6,"6. Caring, leisure and other service occupations",122
356717,W01002040,Vale of Glamorgan 015F,7,7. Sales and customer service occupations,106
356718,W01002040,Vale of Glamorgan 015F,8,"8. Process, plant and machine operatives",66
356719,W01002040,Vale of Glamorgan 015F,9,9. Elementary occupations,51

In [86]:
soc_active_group.Observation.sum()

54457368

In [ ]:
# Aggregate over 75 population and replace soc with does not apply

In [88]:
soc_75_no_age

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
40,E01000001,City of London 001A,-8,Does not apply,131
41,E01000001,City of London 001A,1,"1. Managers, directors and senior officials",3
42,E01000001,City of London 001A,2,2. Professional occupations,11
43,E01000001,City of London 001A,3,3. Associate professional and technical occupa...,5
44,E01000001,City of London 001A,4,4. Administrative and secretarial occupations,0
...,...,...,...,...,...
1783595,W01002040,Vale of Glamorgan 015F,5,5. Skilled trades occupations,0
1783596,W01002040,Vale of Glamorgan 015F,6,"6. Caring, leisure and other service occupations",0
1783597,W01002040,Vale of Glamorgan 015F,7,7. Sales and customer service occupations,0
1783598,W01002040,Vale of Glamorgan 015F,8,"8. Process, plant and machine operatives",0
1783599,W01002040,Vale of Glamorgan 015F,9,9. Elementary occupations,0

In [89]:
soc_inactive_group = soc_75_no_age.groupby(['Lower layer Super Output Areas Code',
                       'Lower layer Super Output Areas']).sum().reset_index()

In [93]:
soc_inactive_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
0,E01000001,City of London 001A,37,"Does not apply1. Managers, directors and senio...",150
1,E01000002,City of London 001B,37,"Does not apply1. Managers, directors and senio...",132
2,E01000003,City of London 001C,37,"Does not apply1. Managers, directors and senio...",114
3,E01000005,City of London 001E,37,"Does not apply1. Managers, directors and senio...",44
4,E01000006,Barking and Dagenham 016A,37,"Does not apply1. Managers, directors and senio...",51
...,...,...,...,...,...
35667,W01002036,Vale of Glamorgan 005G,37,"Does not apply1. Managers, directors and senio...",88
35668,W01002037,Vale of Glamorgan 005H,37,"Does not apply1. Managers, directors and senio...",74
35669,W01002038,Vale of Glamorgan 014G,37,"Does not apply1. Managers, directors and senio...",149
35670,W01002039,Vale of Glamorgan 014H,37,"Does not apply1. Managers, directors and senio...",54
35671,W01002040,Vale of Glamorgan 015F,37,"Does not apply1. Managers, directors and senio...",21

In [91]:
soc_inactive_group.Observation.sum()

5140357

In [94]:
soc_inactive_group['Occupation (current) (10 categories) Code'] = -8

In [95]:
soc_inactive_group['Occupation (current) (10 categories)'] = 'Does not apply'

In [96]:
soc_inactive_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
0,E01000001,City of London 001A,-8,Does not apply,150
1,E01000002,City of London 001B,-8,Does not apply,132
2,E01000003,City of London 001C,-8,Does not apply,114
3,E01000005,City of London 001E,-8,Does not apply,44
4,E01000006,Barking and Dagenham 016A,-8,Does not apply,51
...,...,...,...,...,...
35667,W01002036,Vale of Glamorgan 005G,-8,Does not apply,88
35668,W01002037,Vale of Glamorgan 005H,-8,Does not apply,74
35669,W01002038,Vale of Glamorgan 014G,-8,Does not apply,149
35670,W01002039,Vale of Glamorgan 014H,-8,Does not apply,54
35671,W01002040,Vale of Glamorgan 015F,-8,Does not apply,21

In [ ]:
# merge children+active and inactive together

In [97]:
soc_group = pd.concat([soc_active_group,soc_inactive_group], axis=0)

In [98]:
soc_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
0,E01000001,City of London 001A,-8,Does not apply,481
1,E01000001,City of London 001A,1,"1. Managers, directors and senior officials",191
2,E01000001,City of London 001A,2,2. Professional occupations,396
3,E01000001,City of London 001A,3,3. Associate professional and technical occupa...,178
4,E01000001,City of London 001A,4,4. Administrative and secretarial occupations,38
...,...,...,...,...,...
35667,W01002036,Vale of Glamorgan 005G,-8,Does not apply,88
35668,W01002037,Vale of Glamorgan 005H,-8,Does not apply,74
35669,W01002038,Vale of Glamorgan 014G,-8,Does not apply,149
35670,W01002039,Vale of Glamorgan 014H,-8,Does not apply,54
35671,W01002040,Vale of Glamorgan 015F,-8,Does not apply,21

In [99]:
soc_group.Observation.sum()

59597725

In [11]:
###

43425996

In [100]:
cd I:\NorMITs Land Use\2023\import\ONS-validation

I:\NorMITs Land Use\2023\import\ONS-validation

In [102]:
soc_group.to_csv(r"population_16-74_soc9_lsoa.csv", index=False)