In [1]:
import pandas as pd

In [2]:
# cd I:\NorMITs Land Use\2023\import\ONS-validation\soc_status_active_age

In [3]:
status = pd.read_csv(r"I:\NorMITs Land Use\2023\import\ONS-validation\soc_status_active_age\status_lsoa_16-74.csv")

In [4]:
status

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Age (D) (5 categories) Code,Age (D) (5 categories),Economic activity status (7 categories) Code,Economic activity status (7 categories),Observation
0,E01000001,City of London 001A,1,Aged 15 years and under,-8,Does not apply,125
1,E01000001,City of London 001A,1,Aged 15 years and under,1,Economically active (excluding full-time stude...,0
2,E01000001,City of London 001A,1,Aged 15 years and under,2,Economically active (excluding full-time stude...,0
3,E01000001,City of London 001A,1,Aged 15 years and under,3,Economically active and a full-time student: I...,0
4,E01000001,City of London 001A,1,Aged 15 years and under,4,Economically active and a full-time student: U...,0
...,...,...,...,...,...,...,...
1248515,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,2,Economically active (excluding full-time stude...,0
1248516,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,3,Economically active and a full-time student: I...,0
1248517,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,4,Economically active and a full-time student: U...,0
1248518,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,5,Economically inactive (excluding full-time stu...,21
1248519,W01002040,Vale of Glamorgan 015F,5,Aged 75 years and over,6,Economically inactive and a full-time student,0

In [5]:
status.Observation.sum()

59597486

In [6]:
# Check children do not have SOC
status_children = status[(status['Age (D) (5 categories) Code']==1)&(status['Economic activity status (7 categories) Code']>0)].Observation.sum()
print(status_children)

0

In [7]:
# under 75s
status_74 = status[status['Age (D) (5 categories) Code']<5]

In [8]:
status_74.Observation.sum()

54457214

In [9]:
# 75 and over
status_75 = status[(status['Age (D) (5 categories) Code']==5)]

In [10]:
status_75.Observation.sum()

5140272

In [11]:
status_74.Observation.sum()+status_75.Observation.sum()

59597486

In [12]:
# Remove age bands

In [13]:
status_74_no_age = status_74.drop(status_74.columns[[2, 3]], axis=1)

In [14]:
status_75_no_age = status_75.drop(status_75.columns[[2, 3]], axis=1)

In [15]:
status_74_no_age.Observation.sum()+status_75_no_age.Observation.sum()

59597486

In [16]:
# Aggregate children and active population at zone and status category with no age

In [17]:
status_active_group = status_74_no_age.groupby(['Lower layer Super Output Areas Code',
                       'Lower layer Super Output Areas',
                       'Economic activity status (7 categories) Code',
                       'Economic activity status (7 categories)']).sum().reset_index()

In [18]:
status_active_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Economic activity status (7 categories) Code,Economic activity status (7 categories),Observation
0,E01000001,City of London 001A,-8,Does not apply,125
1,E01000001,City of London 001A,1,Economically active (excluding full-time stude...,837
2,E01000001,City of London 001A,2,Economically active (excluding full-time stude...,32
3,E01000001,City of London 001A,3,Economically active and a full-time student: I...,10
4,E01000001,City of London 001A,4,Economically active and a full-time student: U...,6
...,...,...,...,...,...
249699,W01002040,Vale of Glamorgan 015F,2,Economically active (excluding full-time stude...,35
249700,W01002040,Vale of Glamorgan 015F,3,Economically active and a full-time student: I...,15
249701,W01002040,Vale of Glamorgan 015F,4,Economically active and a full-time student: U...,3
249702,W01002040,Vale of Glamorgan 015F,5,Economically inactive (excluding full-time stu...,205
249703,W01002040,Vale of Glamorgan 015F,6,Economically inactive and a full-time student,41

In [19]:
status_active_group.Observation.sum()

54457214

In [20]:
# Aggregate over 75 population and replace status with Economically inactive 6

In [21]:
status_75_no_age

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Economic activity status (7 categories) Code,Economic activity status (7 categories),Observation
28,E01000001,City of London 001A,-8,Does not apply,0
29,E01000001,City of London 001A,1,Economically active (excluding full-time stude...,19
30,E01000001,City of London 001A,2,Economically active (excluding full-time stude...,0
31,E01000001,City of London 001A,3,Economically active and a full-time student: I...,0
32,E01000001,City of London 001A,4,Economically active and a full-time student: U...,0
...,...,...,...,...,...
1248515,W01002040,Vale of Glamorgan 015F,2,Economically active (excluding full-time stude...,0
1248516,W01002040,Vale of Glamorgan 015F,3,Economically active and a full-time student: I...,0
1248517,W01002040,Vale of Glamorgan 015F,4,Economically active and a full-time student: U...,0
1248518,W01002040,Vale of Glamorgan 015F,5,Economically inactive (excluding full-time stu...,21
1248519,W01002040,Vale of Glamorgan 015F,6,Economically inactive and a full-time student,0

In [22]:
status_inactive_group = status_75_no_age.groupby(['Lower layer Super Output Areas Code',
                       'Lower layer Super Output Areas']).sum().reset_index()

In [23]:
status_inactive_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Economic activity status (7 categories) Code,Observation
0,E01000001,City of London 001A,13,150
1,E01000002,City of London 001B,13,132
2,E01000003,City of London 001C,13,114
3,E01000005,City of London 001E,13,44
4,E01000006,Barking and Dagenham 016A,13,53
...,...,...,...,...
35667,W01002036,Vale of Glamorgan 005G,13,86
35668,W01002037,Vale of Glamorgan 005H,13,74
35669,W01002038,Vale of Glamorgan 014G,13,148
35670,W01002039,Vale of Glamorgan 014H,13,54
35671,W01002040,Vale of Glamorgan 015F,13,21

In [24]:
status_inactive_group.Observation.sum()

5140272

In [25]:
status_inactive_group['Economic activity status (7 categories) Code'] = 5

In [26]:
status_inactive_group['Economic activity status (7 categories)'] = 'Economically inactive (excluding full-time students)'

In [27]:
status_inactive_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Economic activity status (7 categories) Code,Observation,Economic activity status (7 categories)
0,E01000001,City of London 001A,5,150,Economically inactive (excluding full-time stu...
1,E01000002,City of London 001B,5,132,Economically inactive (excluding full-time stu...
2,E01000003,City of London 001C,5,114,Economically inactive (excluding full-time stu...
3,E01000005,City of London 001E,5,44,Economically inactive (excluding full-time stu...
4,E01000006,Barking and Dagenham 016A,5,53,Economically inactive (excluding full-time stu...
...,...,...,...,...,...
35667,W01002036,Vale of Glamorgan 005G,5,86,Economically inactive (excluding full-time stu...
35668,W01002037,Vale of Glamorgan 005H,5,74,Economically inactive (excluding full-time stu...
35669,W01002038,Vale of Glamorgan 014G,5,148,Economically inactive (excluding full-time stu...
35670,W01002039,Vale of Glamorgan 014H,5,54,Economically inactive (excluding full-time stu...
35671,W01002040,Vale of Glamorgan 015F,5,21,Economically inactive (excluding full-time stu...

In [28]:
# merge children+active and inactive together

In [29]:
status_group = pd.concat([status_active_group,status_inactive_group], axis=0)

In [30]:
status_group

,Lower layer Super Output Areas Code,Lower layer Super Output Areas,Economic activity status (7 categories) Code,Economic activity status (7 categories),Observation
0,E01000001,City of London 001A,-8,Does not apply,125
1,E01000001,City of London 001A,1,Economically active (excluding full-time stude...,837
2,E01000001,City of London 001A,2,Economically active (excluding full-time stude...,32
3,E01000001,City of London 001A,3,Economically active and a full-time student: I...,10
4,E01000001,City of London 001A,4,Economically active and a full-time student: U...,6
...,...,...,...,...,...
35667,W01002036,Vale of Glamorgan 005G,5,Economically inactive (excluding full-time stu...,86
35668,W01002037,Vale of Glamorgan 005H,5,Economically inactive (excluding full-time stu...,74
35669,W01002038,Vale of Glamorgan 014G,5,Economically inactive (excluding full-time stu...,148
35670,W01002039,Vale of Glamorgan 014H,5,Economically inactive (excluding full-time stu...,54
35671,W01002040,Vale of Glamorgan 015F,5,Economically inactive (excluding full-time stu...,21

In [31]:
status_group.Observation.sum()

59597486

In [32]:
status_group = status_group.groupby(
    ['Lower layer Super Output Areas Code', 'Lower layer Super Output Areas', 'Economic activity status (7 categories) Code', 'Economic activity status (7 categories)'], as_index=False
).agg({'Observation': 'sum'})

In [33]:
status_group.Observation.sum()

59597486

In [34]:
status_group.to_csv(r"I:\NorMITs Land Use\2023\import\ONS-validation\population_16-74_status_lsoa.csv", index=False)